### PR TITLE
Two lines preventing ps2doom to compile.

### PR DESCRIPTION
**Pull request by dirsors**
The makefile has this lines wich appears to be incorrect:

PS2_LIB_DIR := /home/dfletcher/PS2DEMO/PS2-Development/inc
WIN_DIR := /mnt/c/Users/dflet/Desktop/

They are preventing ps2doom to compile.

make -C ./audsrvx/iop/audsrvx/
make[1]: Entering directory '/home/adilson/skyy/SKYDOOM/linuxdoom-1.10/audsrvx/iop/audsrvx'
Makefile:15: /home/dfletcher/ps2dev/build/ps2sdk/iop/Rules.release: No such file or directory
make[1]: *** No rule to make target '/home/dfletcher/ps2dev/build/ps2sdk/iop/Rules.release'.  Stop.
make[1]: Leaving directory '/home/adilson/skyy/SKYDOOM/linuxdoom-1.10/audsrvx/iop/audsrvx'
make: *** [Makefile:43: compile] Error 2

### CODE REVIEW

**Comment by crypt4489** [comment]
Some of the paths in audsrvx folder are hard coded to my setup with ps2dev. Those should be changed. In order to compile, you need my other PS2 library and have PS2_LIB_DIR point to the header directory for the source. I will change them so they are better soon.

**Comment by dirsors** [comment]
Could you upload a latest build version (ISO or ELF) of the actual project so I can see the progress of the game done so far?

**Comment by crypt4489** [comment]
There is a release. It might need to be scanned by firewall to get pass. Should work on pcsx2. If you get it to work on real hardware, let me know. Will publish makefile fixes tomorrow.

**Comment by dirsors** [comment]
PCSX2 works fine but on real hardware, tested with OPL, it hangs (freeze) at white screen color step startup. The white color has to do with SifInitRpc(0) 
https://github.com/israpps/israpps/blob/main/OPL_EE_CORE_DEBUG_COLORS.MD

**Comment by crypt4489** [comment]
Okay, yeah I figured something might happen. Although, my code doesn't call SifInitRpc(0) (which might be a big) so I'm not sure if that's it. There are also more common reasons for white screen at startup though. https://www.ps2-home.com/forum/viewtopic.php?f=50&t=1040 maybe it is one of those. Anyways won't be able to test until I have my own PS2 up and running. Thanks for trying.

**Comment by dirsors** [comment]
If you want me to do tests on real PS2, feel free to send me the ISO and I'll do it.

**Comment by dirsors** [comment]
Is there any way for me to contact you? I would like to work on my fork of ps2doom and add support for demo playing wich is disabled, for example.

**Comment by crypt4489** [comment]
Fixed compilation issues, now only needs to define the path to your local ps2sdk build.

**Comment by crypt4489** [comment]
> Is there any way for me to contact you? I would like to work on my fork of ps2doom and add support for demo playing wich is disabled, for example.

You can contact me at crypt4489@gmail.com

**Pull request closed without merging**
