### PR TITLE
Update hu_stuff.c

### PR DESCRIPTION
**Pull request by dirsors**

### CODE REVIEW

**Review by crypt4489 — COMMENTED** [review]
I think you might need to change the starting x coordinate along the width of the screen. The start and end of the string should be equal distance from left and right sides of the screen

**Comment by dirsors** [comment]
Unfortunately, I don't know how to do that.
What do you think about just show the message as any other does (upper left of screen)?

**Comment by crypt4489** [comment]
I like having it in the center of the screen for now. That is how I think gzdoom and quake do it. If you want to mess around with the game and change it so the message it fits, it would be just messing around with the first parameter to the text drawing function.

**Comment by dirsors** [comment]
So let's just leave as is. Maybe in the future I'll think about change it. Thanks.

**Pull request closed without merging**
